# Generated by Django 4.0.2 on 2022-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(to='student_classroom.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
